name: Windows build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Windows Builds
    runs-on: windows-2025
    strategy:
      matrix:
        include:
          - windows-arch: 64
            bits: 64
            arch: x86_64
            qtarch: win64_mingw

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download GST Installer
      uses: carlosperate/download-file-action@v2
      id: download-gst
      with:
        file-url: 'https://gstreamer.freedesktop.org/data/pkg/windows/1.27.1/mingw/gstreamer-1.0-mingw-${{ matrix.arch }}-1.27.1.msi'
        file-name: 'gstreamer.msi'
        location: './downloads'

    - name: Download GST-Dev Installer
      uses: carlosperate/download-file-action@v2
      id: download-gst-dev
      with:
        file-url: 'https://gstreamer.freedesktop.org/data/pkg/windows/1.27.1/mingw/gstreamer-1.0-devel-mingw-${{ matrix.arch }}-1.27.1.msi'
        file-name: 'gstreamer-devel.msi'
        location: './downloads'

    - name: Install GST
      shell: powershell
      run: |
        start-process -wait msiexec -argumentlist '/q /i ${{ steps.download-gst.outputs.file-path }} ADDLOCAL=ALL'
        start-sleep 10
        start-process -wait msiexec -argumentlist '/q /i ${{ steps.download-gst-dev.outputs.file-path }} ADDLOCAL=ALL'
        start-sleep 10

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
       version: '6.8.3'
       arch: ${{ matrix.qtarch }}
       modules: 'qtnetworkauth'
       archives: 'qtbase qtsvg'
       tools: 'tools_mingw1310'

    - name: Add Qt MinGW to PATH
      shell: bash
      run: echo "$QT_ROOT_DIR/../../../Tools/mingw1310_64/bin" >> $GITHUB_PATH

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build .

    - name: Create output dir and copy exe
      run: |
        mkdir output
        copy build\openkj.exe output\
      shell: cmd

    - name: Run windeployqt
      shell: cmd
      run: windeployqt --release --compiler-runtime output/openkj.exe

    - name: Copy GStreamer DLLs
      shell: bash
      run: |
        cp -v "C:/Program Files/gstreamer/1.0/mingw_x86_64/bin/"*.dll output/

    - name: Upload bundled artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows ${{ matrix.arch }} binary
        path: output/
